name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - id: date
        run: echo "date=$(date +%s)" >> $GITHUB_OUTPUT
      - run: |
          flyctl deploy --remote-only --build-arg BP_GO_BUILD_LDFLAGS="-X github.com/brattonross/ghostedbot/internal/debug.BuildHash=${{ github.sha }} -X github.com/brattonross/ghostedbot/internal/debug.BuildDate=${{ steps.date.outputs.date }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
